//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XamSample.Resources
{
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources
    {
        #region PRIVATE_VARIABLES

        /// <summary>
        /// Defines the resourceCulture.
        /// </summary>
        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        /// Defines the resourceMan.
        /// </summary>
        private static global::System.Resources.ResourceManager resourceMan;

        /// <summary>
        /// Gets the AvailableQTY
        /// Looks up a localized string similar to Available Qty...
        /// </summary>
        internal static string AvailableQTY
        {
            get
            {
                return ResourceManager.GetString("AvailableQTY", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the Cost
        /// Looks up a localized string similar to Cost...
        /// </summary>
        internal static string Cost
        {
            get
            {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }

        /// <summary>
        /// Gets or sets the Culture
        /// Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class...
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Gets the Description
        /// Looks up a localized string similar to Product Description...
        /// </summary>
        internal static string Description
        {
            get
            {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the Login
        /// Looks up a localized string similar to Login...
        /// </summary>
        internal static string Login
        {
            get
            {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the MaxQty
        /// Looks up a localized string similar to Max Qty...
        /// </summary>
        internal static string MaxQty
        {
            get
            {
                return ResourceManager.GetString("MaxQty", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the Password
        /// Looks up a localized string similar to Password...
        /// </summary>
        internal static string Password
        {
            get
            {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the ProductName
        /// Looks up a localized string similar to Product Name...
        /// </summary>
        internal static string ProductName
        {
            get
            {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the ResourceManager
        /// Returns the cached ResourceManager instance used by this class...
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XamSample.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Gets the Signin
        /// Looks up a localized string similar to Signin...
        /// </summary>
        internal static string Signin
        {
            get
            {
                return ResourceManager.GetString("Signin", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the UserName
        /// Looks up a localized string similar to UserName...
        /// </summary>
        internal static string UserName
        {
            get
            {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }

        #endregion

        #region CONSTRUCTOR

        /// <summary>
        /// Initializes a new instance of the <see cref="AppResources"/> class.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources()
        {
        }

        #endregion
    }
}
